name: Actions 😎

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      # # Compress folder
      # - name: Compress build folder
      #   uses: vimtor/action-zip@v1
      #   with:
      #     files: build
      #     dest: Build.zip

      # - name: Build info
      #   run: echo ${{ github.sha }} > Build.zip

      # - name: Test
      #   run: cat Build.zip

      - name: show folder info
        run: |
          ls -ahl

      # - name: Generate release tag
      #   id: tag
      #   run: |
      #     echo "::set-output name=release_tag::Version_$(date +"%Y.%m.%d_%H-%M")"

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ steps.tag.outputs.release_tag }}
      #     files: Build.zip
